# Generated by Django 5.0.7 on 2024-07-31 16:09

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="embedding",
            field=pgvector.django.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
    ]
