# Generated by Django 5.0.7 on 2024-07-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_blogpost_can_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
